language: python
python:
- '3.6'
env:
- DJANGO_SETTINGS_MODULE=config.settings.local
install:
- pip install pipenv
- pipenv install --dev
script:
- python app/manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_4e06998d5487_key -iv $encrypted_4e06998d5487_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
